language: php

php:
  - 5.6

notifications:
  slack:
    rooms:
      - avanssog:izJRGcESzpQkjcYmzuYvPoXR
    on_succes: change

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer install --no-interaction --prefer-source -v

before_script:
  - cp .env.travis .env

script: vendor/bin/phpunit
