//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Domain
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Field
	{
		public virtual Field Next
		{
			get;
			set;
		}

		public virtual PlayingGround PlayingGround
		{
			get;
			set;
		}

	}
}

