//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Domain
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class PlayingGround
	{
		public virtual Dictionary<char, Track> Warehouses
		{
			get;
			set;
		}

		public virtual Water Dock
		{
			get;
			set;
		}

		public virtual List<Cart> Carts
		{
			get;
			set;
		}

		public virtual Dictionary<int, Switch> Switches
		{
			get;
			set;
		}

		public virtual Ship Ship
		{
			get;
			set;
		}

		public virtual Game Game
		{
			get;
			set;
		}

		public virtual void MoveSwitch(int id)
		{
			throw new System.NotImplementedException();
		}

	}
}

