//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Domain
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Reviver
	{
		public static PlayingGround GeneratePlayingGround()
		{
			get;
			set;
		}

		public virtual Game Game
		{
			get;
			set;
		}

	}
}

