//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Domain
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class Switch : Track
	{
		public virtual StateType State
		{
			get;
			set;
		}

		public virtual Track Top
		{
			get;
			set;
		}

		public virtual Track Bottom
		{
			get;
			set;
		}

		public virtual int Id
		{
			get;
			set;
		}

		public override bool IsOccupied
		{
			get;
			set;
		}

		public override bool MayCollide
		{
			get;
			set;
		}

		public virtual bool CanBeSwitched()
		{
			throw new System.NotImplementedException();
		}

		public virtual void SwitchState()
		{
			throw new System.NotImplementedException();
		}

	}
}

