//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Domain
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Track : Field
	{
		public virtual Track Next
		{
			get;
			set;
		}

		public virtual bool IsOccupied
		{
			get;
			set;
		}

		public virtual Dock Dock
		{
			get;
			set;
		}

		public virtual bool MayCollide
		{
			get;
			set;
		}

		public virtual void DismissCart()
		{
			throw new System.NotImplementedException();
		}

	}
}

