//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Domain
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Yard : Track
	{
		public override bool IsOccupied
		{
			get;
			set;
		}

		public override bool MayCollide
		{
			get;
			set;
		}

		public override Track Next
		{
			get;
			set;
		}

		public override void DismissCart()
		{
			throw new System.NotImplementedException();
		}

	}
}

