os: osx

osx_image: xcode9

language: cpp

install:
  - brew update
  - brew upgrade cmake
  - brew install sdl2 sdl2_ttf sdl2_image sdl2_mixer

before_script:
  - mkdir build && cd build

script:
  - cmake ..
  - make
