//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Views
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class InputView : IViewInterface
	{
		public static void PrintGameInstruction()
		{
			throw new System.NotImplementedException();
		}

		public static void PrintGameStart()
		{
			throw new System.NotImplementedException();
		}

	}
}

