//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Views
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class OutputView
	{
		public static void PrintWelcomeMessage()
		{
			throw new System.NotImplementedException();
		}

		public static void PrintBoat()
		{
			throw new System.NotImplementedException();
		}

		public static void PrintPlayground()
		{
			throw new System.NotImplementedException();
		}

		public static void PrintEndGame()
		{
			throw new System.NotImplementedException();
		}

	}
}

