//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionInspector
    {
        public int InspectorID { get; set; }
        public int InspectionID { get; set; }
        public int NumParkingSpacesOccupied { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string Remarks { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Inspection Inspection { get; set; }
    }
}
