//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingLot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParkingLot()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int ID { get; set; }
        public Nullable<double> GeoLatitude { get; set; }
        public Nullable<double> GeoLongitude { get; set; }
        public Nullable<int> NumCameras { get; set; }
        public Nullable<int> NumParkingSpaces { get; set; }
        public Nullable<System.DateTime> DateOpened { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public Nullable<bool> HasBarrier { get; set; }
        public Nullable<bool> HasFence { get; set; }
        public Nullable<int> ParkingFeeHourly { get; set; }
        public Nullable<int> ParkingFeeMax { get; set; }
        public string Hash { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
