//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int ID { get; set; }
        public string Filename { get; set; }
        public string Image { get; set; }
        public string Remarks { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Inspection Inspection { get; set; }
    }
}
