//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.AnswerSetValues = new HashSet<AnswerSetValue>();
            this.Answers = new HashSet<Answer>();
            this.ChecklistQuestions = new HashSet<ChecklistQuestion>();
        }
    
        public int ID { get; set; }
        public string Text { get; set; }
        public string AnswerPrefix { get; set; }
        public string AnswerSuffix { get; set; }
        public bool Prebuilt { get; set; }
        public string Remarks { get; set; }
        public string Hash { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerSetValue> AnswerSetValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChecklistQuestion> ChecklistQuestions { get; set; }
        public virtual QuestionType QuestionType { get; set; }
    }
}
