//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskSchedule()
        {
            this.Interval = 1;
        }
    
        public int ID { get; set; }
        public System.DateTime InspectionDateTime { get; set; }
        public int Interval { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual IntervalFrequency IntervalFrequency { get; set; }
    }
}
