//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Controllers
{
	using Domain;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class GameController
	{
		public object Game;

		public virtual Game Game
		{
			get;
			set;
		}

		private ConsoleKey AskInput()
		{
			throw new System.NotImplementedException();
		}

		private void PlayGame()
		{
			throw new System.NotImplementedException();
		}

	}
}

